### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by klaseskilson**
56 commits yo!

### CODE REVIEW

**Comment by klaseskilson** [comment]
:bee:R @tistatos @danielronnkvist

**Comment by tistatos** [comment]
Looks good to me, @danielronnkvist why don't you take a look?

**Comment by danielronnkvist** [comment]
Got an error of invalid date on the `month` method... The update path had been overwritten when I implemented the month method.. Fixed in a new commit. Otherwise it looks fine! :100: :beer:

**Comment by klaseskilson** [comment]
Cool. Will merge + deploy!

**Pull request merged**
