### PR TITLE
Fix/rubocop issues

### PR DESCRIPTION
**Pull request by klaseskilson**
ftp

### CODE REVIEW

**Comment by danielronnkvist** [comment]
Looks good to me! But isn't travis going to fail on those 14 offenses like it failed in #142?

**Comment by klaseskilson** [comment]
Probably yes. Not really sure what to do about those errors though, they're mostly in `BookingsController` and complexity related. Not the easiest things to fix imo, but I can take a look at it.

**Comment by danielronnkvist** [comment]
Ah shit. Yes that's some work to do on that controller...

**Comment by klaseskilson** [comment]
It is. I suggest we temporarily ignore that specific file in Rubocop so that deployment won't be blocked by it.

**Comment by klaseskilson** [comment]
@danielronnkvist! Solution ok? ☝️

**Comment by klaseskilson** [comment]
🎉

**Pull request merged**
