### PR TITLE
Improve booking feedback

### PR DESCRIPTION
**Pull request by klaseskilson**
This improves the feedback that the user is given when creating a new booking. It also replaces Users with Bookings on the admin dashboard. Related to #91.

Some screen shots:

screen shot 2016-02-09 at 22 38 30
screen shot 2016-02-09 at 22 40 11

### CODE REVIEW

**Comment by klaseskilson** [comment]
I've got some tweaks for this one coming up in a couple of minutes

**Comment by klaseskilson** [comment]
Just added this:
screen shot 2016-02-10 at 22 26 36

**Comment by tistatos** [comment]
perhaps @danielronnkvist can take a look at this, I'm not familiar with previous feedback of booking system.

**Comment by danielronnkvist** [comment]
I get the red box shadow when I enter the form from the beginning. Shouldn't it only be visible when the form has been submitted?

screen shot 2016-02-16 at 19 26 05

**Comment by klaseskilson** [comment]
I agree that would be better if the borders were red only after the user has interacted with them, but that's not how the pseudo class that I am using works. I thought that together with the asterisk, it would not come across as too discouraging. I have a tiny hack that might fix this though. I'll try and see if it works.

**Comment by klaseskilson** [comment]
@danielronnkvist, how does it look now?

**Comment by danielronnkvist** [comment]
WOOOHOOOO

**Pull request merged**
