### PR TITLE
Feature/improved all drinks

### LINKED ISSUE #83: Improvments to "all drinks" view
This view should:
- Be sortable
- look prettier (background is too short for content)
- divide drinks into two categories, (in-stock, out of stock)

### PR DESCRIPTION
**Pull request by tistatos**
This fixes #83.

View is now sortable by name brewery country percentage and price.
View is also automagically sorted to put out of stock drinks in the bottom

### CODE REVIEW

**Comment by klaseskilson** [comment]
I think we should truncate the description of the beer, since some of them are very long.

**Comment by tistatos** [comment]
Yes, not really important in this view anyways?

**Comment by klaseskilson** [comment]
I guess we can remove it from the overview if you feel that is the best solution. :thumbsup:

**Comment by tistatos** [comment]
removed description and synced with develop and master

**Comment by klaseskilson** [comment]
Good job! :beer:

**Comment by tistatos** [comment]
My work here is done - time for beer

**Pull request merged**
