### PR TITLE
Feature/account for stock changing

### PR DESCRIPTION
**Pull request by klaseskilson**
This allows non-admin users to edit the stock status of a drink. It adds a semi-ugly `check_admin` method to `DrinksController`, which isn't that nice. (It was the simplest solution I could think of though.)

### CODE REVIEW

**Comment by tistatos** [comment]
I think this is also the simplest solution for now, in the future we could also look into changing to cancancan IF it has the support we need for the users to be able to change stock status

**Comment by klaseskilson** [comment]
@tistatos Totally agree. Cancancan is probably the next step since cancan hasn't been updated in ages. However, I think we should get this feature ready as soon as possible, since there is a new period for the staff now. Would be great to keep the stock as up to date as possible. :beer:

**Comment by tistatos** [comment]
I'll give this a spin when I come home today unless @danielronnkvist jumps in and snipes the approval

**Comment by tistatos** [comment]
As used to how to navigate as an admin, it was a bit tricky to find where to find the view to edit stock status.

Is it possible to keep the "admin: drycker" link when you enter sortiment view?

**Comment by klaseskilson** [comment]
Sounds like a good idea! Fix coming up.

**Comment by tistatos** [comment]
:+1: PRA GJORT!

**Pull request merged**
