### PR TITLE
Rename booking route, fix #110

### LINKED ISSUE #110: Bookings has an english URL endpoint
Should be called _bokningar_ or something similar to match the rest of the site. But keep the bookings path so we don't break links.

### PR DESCRIPTION
**Pull request by klaseskilson**
This changes the public url endpoints to Swedish for the booking thingies.

### CODE REVIEW

**Comment by tistatos** [comment]
Part of the Issue description was to keep old routes but it seems like they dont work now.

**Comment by klaseskilson** [comment]
Do you think we need to keep them? Why?
  
  
  

  
  
>

**Comment by tistatos** [comment]
@danielronnkvist , what do you think?

**Comment by klaseskilson** [comment]
I think we can ditch the old urls, I don't think they're used that much. Mostly from emails and such, and it is such a low volume that we can take that hit imo.

**Comment by tistatos** [comment]
I think so too. since the only links that will no longer work are older with link to admins.

looks good to me :ship: :it:

**Comment by klaseskilson** [comment]
Merging. If we some how realise this is bad, we'll revert. 💥

**Pull request merged**
