### PR TITLE
Add CI deployment instructions

### PR DESCRIPTION
**Pull request by klaseskilson**

### CODE REVIEW

**Comment by tistatos** [comment]
So if I understand it right: travis will push to heroku?

**Comment by klaseskilson** [comment]
Yes! On both master and develop.
  
  
  

  
  
>

**Comment by klaseskilson** [comment]
@tistatos So that we won't have to. Super simple and will probably help us deploy more often!

**Comment by danielronnkvist** [comment]
Shouldn't the master and development application be placed under deploy > app? If I understand the [travis docs](https://docs.travis-ci.com/user/deployment/heroku/#Deploying-Custom-Application-Names) correctly.

**Comment by klaseskilson** [comment]
You are super correct! Will fix and then merge. 👌

**Comment by danielronnkvist** [comment]
Looks good to me 👍 🎉

**Pull request merged**
