### PR TITLE
Feature/fix auto beer info

### PR DESCRIPTION
**Pull request by tistatos**
This should do out!

### CODE REVIEW

**Comment by klaseskilson** [comment]
Looks good! I think we should add `autocomplete="off"` to the beer name tag, to prevent this:

screen shot 2016-02-21 at 15 49 18

**Comment by danielronnkvist** [comment]
How come @mention-bot still identifies @CarlEnglund to be a potential reviewer?

**Comment by klaseskilson** [comment]
I have no idea!

**Comment by tistatos** [comment]
Since he is still a contributor? I guess it looks on file commit history to check who to tag

**Comment by klaseskilson** [comment]
That is true, but he is ignored in the [mention bot config](https://github.com/klaseskilson/vattentornet/blob/master/.mention-bot).

**Comment by tistatos** [comment]
blacklist is one word ;)

**Comment by tistatos** [comment]
Fixed the "L" on develop, PR to master?

**Comment by klaseskilson** [comment]
Ah! Good catch.

**Comment by klaseskilson** [comment]
(wrong issue number! in that commit.)

**Pull request merged**
