### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by klaseskilson**
Let's get those updates deployed! :beer:

### CODE REVIEW

**Comment by klaseskilson** [comment]
:beers: :beer: :beers: :beer: :beers: :beer: :beers: :beer: :beers:  @CarlEnglund! @danielronnkvist! :beers: :beer: :beers: :beer: :beers: :beer: :beers: :beer: :beers:

**Comment by danielronnkvist** [comment]
:beers: @CarlEnglund kanske då jag gjort grejer här! :beer:

**Comment by danielronnkvist** [comment]
:bee: r

**Comment by CarlEnglund** [comment]
Looks good to me! :sparkling_heart:

**Pull request merged**
